apiVersion: v1
kind: Service
metadata:
  name: {{ include "roboshop.fullname" . }}
  labels:
    {{- include "roboshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "roboshop.selectorLabels" . | nindent 4 }}
